var markers = [{
        "name": "Google",
        "contact_number": "95686958659",
        "type": "",
        "url": "https://en.wikipedia.org/wiki/Google",
        "lat": "37.422",
        "lng": "-122.084",
        "Mailing_Street": "1600 Amphitheatre Parkway",
        "Mailing_PO_Box": "",
        "Mailing_City": "Mountain View",
        "Mailing_State": "CA",
        "Mailing_Zip": "94043",
        "Mailing_Country": "USA",
        // "show_circle": true
    },
    {
        "name": "Apple",
        "contact_number": "95686958659",
        "type": "",
        "url": "https://en.wikipedia.org/wiki/Apple",
        "lat": "",
        "lng": "",
        "Mailing_Street": "1 Infinite Loop",
        "Mailing_PO_Box": "",
        "Mailing_City": "Cupertino",
        "Mailing_State": "CA",
        "Mailing_Zip": "95014",
        "Mailing_Country": "USA"
    },
    {
        "name": "S.T.S.Prasad",
        "contact_number": "95686958659",
        "type": "",
        "url": "https://en.wikipedia.org/wiki/Apple",
        "lat": "",
        "lng": "",
        "Mailing_Street": "15225, Blue Gum Ct",
        "Mailing_PO_Box": "",
        "Mailing_City": "Saratoga",
        "Mailing_State": "CA",
        "Mailing_Zip": "95070",
        "Mailing_Country": "USA"
    },
    {
        "name": "Disneyland Park",
        "contact_number": "95686958659",
        "type": "",
        "url": "https://en.wikipedia.org/wiki/Apple",
        "lat": "",
        "lng": "",
        "Mailing_Street": "1313 Disneyland Dr",
        "Mailing_PO_Box": "",
        "Mailing_City": "Anaheim",
        "Mailing_State": "CA",
        "Mailing_Zip": "92802",
        "Mailing_Country": "USA"
    },
    {
        "name": "Smithsonian Institute",
        "contact_number": "95686958659",
        "type": "",
        "url": "https://en.wikipedia.org/wiki/Apple",
        "lat": "",
        "lng": "",
        "Mailing_Street": "600 Maryland Ave SW",
        "Mailing_PO_Box": "",
        "Mailing_City": "Washington",
        "Mailing_State": "DC",
        "Mailing_Zip": "20002",
        "Mailing_Country": "USA"
    },
    {
        "name": "Facebook",
        "contact_number": "95686958659",
        "type": "",
        "url": "https://en.wikipedia.org/wiki/Facebook",
        "lat": "",
        "lng": "",
        "Mailing_Street": "1 Hacker Way",
        "Mailing_PO_Box": "",
        "Mailing_City": "Menlo Park",
        "Mailing_State": "CA",
        "Mailing_Zip": "94025",
        "Mailing_Country": "USA"
    }
];